name: update-chromium
on:
  schedule:
    # cron job that will run 1st and 15th of every month by 12am
    # - cron:  '2 12 1,15 * *'
    - cron:  '5/5 * * * *'

jobs:
  update-to-latest-chromium:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Get Chromium version and update
        run: |
          npm install
          node updateChromium.js
          revision=$(cat package.json | grep chromium_revision | awk '{print $2}' | sed 's/[",]//g')
          echo "::set-env name=REVISION::$revision"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GAUGEBOT_GITHUB_TOKEN }}
          branch: ${{format('{0}{1}', 'update-chromium',env.REVISION)}}
          commit-message: ${{format('{0}{1}','Update chromium to revision ', env.REVISION)}}
          title: ${{format('{0}{1}','Update chromium to revision ', env.REVISION)}}